set(CPACK_PACKAGE_NAME ${PROJECT_NAME})

set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "CPACK example of the exercise of the course SSE WS25/26 at the university of Stuttgart. Demonstration how to use cpack for tar.gz and .deb packages.")
set(CPACK_PACKAGE_VENDOR "Silas Müller")
set(CPACK_PACKAGE_CONTACT "st187141@stud.uni-stuttgart.de")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "CPACK exercise SSE WS25/26")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/silasmue/cpack-exercise-wt2526")
set(CPACK_GENERATOR "TGZ;DEB")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Silas Müller st187141@stud.uni-stuttgart.de")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libboost-filesystem1.83.0, libdeal.ii-dev")
set(CPACK_STRIP_FILES TRUE)
include(CPack)
